export const GAMES = [
  "RollerCoin",
  "The Sandbox",
  "Decentraland",
  "Axie Infinity",
  "Gala Games",
  "Enjin Coin",
  "STEPN",
  "Treasure",
  "Ankr",
  "Wilder World",
  "PlayDapp",
  "My Neighbor Alice",
  "Vulcan Forged",
  "MOBOX",
  "Murasaki",
  "Clash Of Lilliput",
  "Gelato",
  "Alien Worlds",
  "Ultra",
  "Aavegotchi",
  "Radio Caca",
  "SweatCoin",
  "Victoria VR",
  "League of Kingdoms",
  "Gods Unchained",
  "HiFi Gaming Society"
]